"""Application services for generation, review, output, and progress flows."""

from .batching import BatchExecutionResult, BatchExecutionSettings, chunk_tasks, execute_task_batch
from .benchmark_planning import (
    build_benchmark_combinations,
    build_explicit_benchmark_combinations,
    build_generated_benchmark_combinations,
    normalize_judge_slots,
    pad_judge_keys,
)
from .adjudication import arbitrate_case_with_fallbacks, build_rule_blocked_final_metrics
from .benchmarking import (
    aggregate_judge_rows,
    build_benchmark_detail_base_row,
    build_benchmark_summary_row,
    build_benchmark_summary_context,
    build_benchmark_summary_context_key,
    build_generation_failure_judge_rows,
    build_judge_columns,
    collect_benchmark_summary_rows,
    compute_label,
    normalize_benchmark_judge_result,
)
from .case_processing import (
    build_case_error_result,
    build_case_result_base,
    build_completed_case_result,
    apply_final_quality_gates,
    build_rule_blocked_result,
    select_final_metrics,
    should_require_arbitration,
)
from .generation import (
    apply_generation_strategy_metadata,
    build_completion_visible_metadata,
    build_staged_generation_result,
    merge_staged_generation_metadata,
    merge_staged_generation_result,
    normalize_generation_case,
    normalize_stage_generator_configs,
    resolve_stage_generator_configs,
    run_generation_with_strategy,
    run_single_generation,
    run_staged_generation,
)
from .progress import (
    build_batch_progress_message,
    build_completion_summary_context,
    build_failure_log_message,
    build_stage_summary_context,
    build_stage_summary_lines,
    build_stage_summary_lines_from_context,
    summarize_results,
)
from .review import (
    build_model_fallback_chain,
    compute_score_difference,
    evaluate_case_with_fallbacks,
    evaluate_case_with_mode,
    evaluate_deepeval_case,
    evaluate_rule_base_case,
    normalize_judge_result,
    normalize_score,
    normalize_total_score,
    resolve_evaluation_mode,
)
from .task_planning import build_case_tasks, filter_pending_tasks, resolve_milestones, resolve_parallel_count

__all__ = [
    "BatchExecutionResult",
    "BatchExecutionSettings",
    "aggregate_judge_rows",
    "apply_generation_strategy_metadata",
    "apply_final_quality_gates",
    "arbitrate_case_with_fallbacks",
    "build_benchmark_combinations",
    "build_benchmark_detail_base_row",
    "build_batch_progress_message",
    "build_benchmark_summary_row",
    "build_benchmark_summary_context",
    "build_benchmark_summary_context_key",
    "build_case_error_result",
    "build_case_tasks",
    "build_case_result_base",
    "build_completed_case_result",
    "build_completion_summary_context",
    "build_completion_visible_metadata",
    "build_explicit_benchmark_combinations",
    "build_failure_log_message",
    "build_generated_benchmark_combinations",
    "build_generation_failure_judge_rows",
    "build_judge_columns",
    "build_model_fallback_chain",
    "build_rule_blocked_final_metrics",
    "build_rule_blocked_result",
    "build_stage_summary_context",
    "build_stage_summary_lines",
    "build_stage_summary_lines_from_context",
    "build_staged_generation_result",
    "chunk_tasks",
    "collect_benchmark_summary_rows",
    "compute_label",
    "compute_score_difference",
    "execute_task_batch",
    "evaluate_rule_base_case",
    "evaluate_case_with_fallbacks",
    "evaluate_case_with_mode",
    "evaluate_deepeval_case",
    "filter_pending_tasks",
    "merge_staged_generation_metadata",
    "merge_staged_generation_result",
    "normalize_generation_case",
    "normalize_benchmark_judge_result",
    "normalize_judge_result",
    "normalize_judge_slots",
    "normalize_score",
    "normalize_stage_generator_configs",
    "normalize_total_score",
    "pad_judge_keys",
    "resolve_milestones",
    "resolve_evaluation_mode",
    "resolve_parallel_count",
    "resolve_stage_generator_configs",
    "run_generation_with_strategy",
    "run_single_generation",
    "run_staged_generation",
    "select_final_metrics",
    "should_require_arbitration",
    "summarize_results",
]
