from __future__ import annotations

# LLM Wiki 基础设施包的公开门面。
#
# 把导入集中放在这里，可以给应用层提供一个稳定入口。应用层只需要从本包
# 导入函数，就能完成 Wiki 上下文加载、来源摄取、权威来源发现、图谱重建、
# 健康检查、契约检查和审计元数据记录，而不必了解每个底层模块的文件位置。

from .wiki import (
    DEFAULT_LLM_WIKI_CONTEXT,
    LlmWikiKnowledgeBase,
    LlmWikiPage,
    LlmWikiSearchHit,
    build_llm_wiki_context,
    clear_llm_wiki_cache,
    load_llm_wiki,
    resolve_llm_wiki_dir,
)
from .audit import build_wiki_audit_metadata, compact_wiki_audit_for_csv
from .authority import (
    AuthorityCandidate,
    AuthoritySourceReport,
    allowed_authority_domains,
    authority_level_for_url,
    discover_authority_sources,
    is_authoritative_url,
)
from .operations import (
    LlmWikiLintReport,
    LlmWikiStatusReport,
    WikiInitReport,
    build_runtime_context,
    build_status_report,
    check_adapter,
    check_cache,
    coverage_report,
    digest_wiki,
    ingest_source,
    ingest_text_source,
    ingest_url_source,
    init_wiki,
    lint_wiki,
    list_sources,
    match_source,
    query_wiki,
    save_query_result,
    source_create,
    update_cache,
    validate_step1_analysis,
)
from .graph import GraphBuildResult, build_graph_data, rebuild_graph, render_graph_html, render_mermaid_graph, watch_graph
from .governance import (
    WikiChangeRequest,
    WikiGovernanceEvent,
    append_governance_event,
    classify_change_semantics,
    validate_change_request as validate_wiki_change_request,
)
from .lifecycle import (
    BatchIngestReport,
    CrystallizeResult,
    DeleteSourceReport,
    WikiCompatReport,
    batch_ingest_sources,
    crystallize_session,
    delete_source,
    inspect_compat,
)
from .maintenance import (
    DEFAULT_API_KEY_ENV,
    DEFAULT_MAINTENANCE_QUERIES,
    DEFAULT_NONELINEAR_BASE_URL,
    DEFAULT_NONELINEAR_MODEL,
    DailyMaintenanceReport,
    MaintenanceTopic,
    NonelinearAuthorityClient,
    build_gap_first_maintenance_queries,
    build_maintenance_queries,
    run_daily_maintenance,
)
from .review import CandidateReviewReport, review_candidate_facts
from .schema import DEFAULT_SCHEMA_PATH, LlmWikiSchemaCheckReport, schema_check

__all__ = [
    "DEFAULT_API_KEY_ENV",
    "DEFAULT_LLM_WIKI_CONTEXT",
    "DEFAULT_MAINTENANCE_QUERIES",
    "DEFAULT_NONELINEAR_BASE_URL",
    "DEFAULT_NONELINEAR_MODEL",
    "DEFAULT_SCHEMA_PATH",
    "GraphBuildResult",
    "BatchIngestReport",
    "AuthorityCandidate",
    "AuthoritySourceReport",
    "CandidateReviewReport",
    "CrystallizeResult",
    "DeleteSourceReport",
    "DailyMaintenanceReport",
    "MaintenanceTopic",
    "LlmWikiLintReport",
    "LlmWikiKnowledgeBase",
    "LlmWikiPage",
    "LlmWikiSearchHit",
    "LlmWikiSchemaCheckReport",
    "LlmWikiStatusReport",
    "WikiInitReport",
    "WikiCompatReport",
    "WikiChangeRequest",
    "WikiGovernanceEvent",
    "NonelinearAuthorityClient",
    "append_governance_event",
    "classify_change_semantics",
    "batch_ingest_sources",
    "allowed_authority_domains",
    "authority_level_for_url",
    "build_graph_data",
    "build_llm_wiki_context",
    "build_maintenance_queries",
    "build_gap_first_maintenance_queries",
    "build_runtime_context",
    "build_status_report",
    "build_wiki_audit_metadata",
    "check_adapter",
    "check_cache",
    "clear_llm_wiki_cache",
    "compact_wiki_audit_for_csv",
    "crystallize_session",
    "delete_source",
    "discover_authority_sources",
    "coverage_report",
    "digest_wiki",
    "ingest_source",
    "ingest_text_source",
    "ingest_url_source",
    "inspect_compat",
    "is_authoritative_url",
    "init_wiki",
    "lint_wiki",
    "list_sources",
    "load_llm_wiki",
    "match_source",
    "query_wiki",
    "rebuild_graph",
    "resolve_llm_wiki_dir",
    "render_graph_html",
    "render_mermaid_graph",
    "review_candidate_facts",
    "run_daily_maintenance",
    "save_query_result",
    "schema_check",
    "source_create",
    "update_cache",
    "validate_step1_analysis",
    "validate_wiki_change_request",
    "watch_graph",
]
